version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=iDRBT@007  # Change to your desired root password
      - MYSQL_DATABASE=users_info,accounts_info  # Change to create the desired databases
    ports:
      - "3306:3306"  # Map the MySQL port to the host (adjust as needed)
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

