apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
spec:
  replicas: 1 # You can adjust this as needed
  selector:
    matchLabels:
      app: accounts-service
  template:
    metadata:
      labels:
        app: accounts-service
    spec:
      containers:
      - name: accounts
        image: pavan0077/vnc-accounts:v1
        ports:
          - containerPort: 9901

